# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

right_format = """$kubernetes $time"""

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
error_symbol = "[✗](bold red)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[azure]
disabled = true
format = 'on [$symbol($subscription)]($style) '
symbol = 'ﴃ '
style = 'blue bold'

[kubernetes]
format = 'on [  $context|$namespace](bright-purple) '
disabled = false

[git_branch]
symbol = "🌱 "

[git_commit]
tag_symbol = "🔖 "

[git_status]
conflicted = "="
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
up_to_date = "✓"
untracked = "?"
stashed = "$"
modified = "🛠️ x${count} "
staged = '[++\($count\)](green)'
renamed = "»"
deleted = '🗑️ ×${count}'

[nodejs]
format = ''
detect_folders = ['!/Users/Jan.Wacker']

[terraform]
format = '[🏎 💨 $workspace]($style) '
style = 'bold 105'

[time]
disabled = false
format = '$time'
time_format = '%T'
utc_time_offset = '+2'


